FROM maven:3.9.11-eclipse-temurin-21 AS builder
WORKDIR /app

# Get and cache dependecies
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn
RUN ./mvnw dependency:go-offline -B

COPY src src
RUN ./mvnw clean package

FROM eclipse-temurin:21-jre-alpine AS runner
WORKDIR /app
COPY --from=builder /app/target/*.jar spring-admin.jar
EXPOSE 8080
ENTRYPOINT exec java -jar spring-admin.jar